services:
  app:
    container_name: carteira_financeira_app
    build: .
    command: ./.docker/start.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app

  db:
    image: mysql:8.0.30-debian
    container_name: carteira_financeira_db
    environment:
      MYSQL_DATABASE: carteira_financeira
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: rabbitmq
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  mysql_data:
